const mongoose=require('mongoose')
var FZSchema=new mongoose.Schema({
		name:{
            required:true,
            type:String
        },
        age:{
            required:true,
            type:String
        },
        name:{
            type:String,
            required:true
        },
        sex:{
            type:String,
            required:true
        },
        address:{
            type:String,
            required:true
        },
        phone:{
            type:String,
            required:true
        },
        sfzhm:{
            type:String,
            required:true
        },
        yj:{
            type:String,
            required:true
        },
        rzsj:{
            type:String,
            required:true
        },
        dqsj:{
            type:String,
            required:true
        },
        sysj:{
            type:String
        },
        fz:{
            type:String,
            required:true
        },
        bz:{
            type:String,
            required:true
        },
})
var FZ=mongoose.model('FZ',FZSchema)
module.exports=FZ
